$server_script = <<-SCRIPT
# Configuración básica de seguridad
sudo ufw disable

# Configuración de hosts
sudo echo "192.168.56.110  mmateoS" | sudo tee -a /etc/hosts

# Instalación de K3s
curl -sfL https://get.k3s.io | sh -s - server --node-ip=192.168.56.110

# Esperar a que K3s esté listo
echo "Esperando que K3s esté listo..."
sleep 30
until sudo k3s kubectl get node | grep -q " Ready"; do
  sleep 5
  echo "Aún esperando que K3s esté listo..."
done

# Verificar la instalación de K3s
if ! command -v kubectl &> /dev/null; then
    echo "Error: K3s no se instaló correctamente"
    exit 1
fi

# Aplicar configuraciones de Kubernetes
echo "Aplicando configuraciones de Kubernetes..."
kubectl apply -f /vagrant/k3s-configs/traefik/app-ingress.yml
kubectl apply -f /vagrant/k3s-configs/app-one/app1.yml
kubectl apply -f /vagrant/k3s-configs/app-two/app2.yml
kubectl apply -f /vagrant/k3s-configs/app-three/app3.yml

# Mostrar estado final
echo "Estado final del cluster:"
kubectl get all
SCRIPT

$box = "ubuntu/focal64"  # Ubuntu 20.04 (Focal Fossa)
$server_memory = "2048"  # Set memory to 2048 MB (2 GB)
$server_cpus = 2  # Set CPUs to 2

# Specify Vagrant configuration version
Vagrant.configure("2") do |config|

  # Define the first virtual machine
  config.vm.define "mmateoS" do |vm1|
    vm1.vm.box = $box  # Ubuntu 20.04 (Focal Fossa)
    vm1.vm.network "private_network", ip: "192.168.56.110"
    vm1.vm.provision "shell", inline: $server_script
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = $server_memory  # Set memory to 2048 MB
      vb.cpus = $server_cpus  # Set CPUs to 2
    end
  end

end

